# Generated by Django 5.0.4 on 2024-04-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='money_collections/previews')),
                ('active', models.BooleanField(default=True)),
                ('collected_amount_on_jar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collected_amount_on_platform', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collected_amount_from_other_requisites', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='reports/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ReportVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyCollectionRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monobank_jar_link', models.URLField()),
                ('monobank_jar_number', models.CharField(blank=True, max_length=16)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bitcoin_wallet_address', models.CharField(blank=True, max_length=42, null=True)),
                ('ethereum_wallet_address', models.CharField(blank=True, max_length=42, null=True)),
                ('usdt_wallet_address', models.CharField(blank=True, max_length=34, null=True)),
                ('bank_cards', models.ManyToManyField(blank=True, related_name='money_collection_requisites', to='money_collections.bankcard')),
                ('money_collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='money_collections.moneycollection')),
                ('other_requisites', models.ManyToManyField(blank=True, related_name='money_collection_requisites', to='money_collections.otherrequisite')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('money_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='money_collections.moneycollection')),
                ('images', models.ManyToManyField(blank=True, related_name='reports', to='money_collections.reportimage')),
                ('videos', models.ManyToManyField(blank=True, related_name='reports', to='money_collections.reportvideo')),
            ],
        ),
    ]
