# Generated by Django 5.0.4 on 2024-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationrequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approwed'), ('d', 'Declined')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='organizationrequest',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
