# Generated by Django 5.0.4 on 2024-05-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_verified_organizationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrequest',
            name='EGRPOU_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
