# Generated by Django 5.0.4 on 2024-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='declined_request_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
